"""added buildtime to blueprint

Revision ID: 0020f481c86d
Revises: 7c72288cfcca
Create Date: 2024-04-01 13:51:53.181118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '0020f481c86d'
down_revision = 'e45e77b4563c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buildtime', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


    # Now a bit of data migration
    from src.model.blueprint import Blueprint
    from src.model.enums import BlueprintType
    print("INFO: Migrating data for buildtime")
    session = Session(bind=op.get_bind())
    for blueprint in session.query(Blueprint).all():
        print("INFO: Setting buildtime for blueprint", blueprint.id)
        if blueprint.id == BlueprintType.ALTAR:
            blueprint.buildtime = 0
        elif blueprint.id == BlueprintType.MINE:
            blueprint.buildtime = 60 * 5 # 5 minutes
        elif blueprint.id == BlueprintType.TOWER:
            blueprint.buildtime = 60 * 10 # 10 minutes
        elif blueprint.id == BlueprintType.FUSE_TABLE:
            blueprint.buildtime = 60 * 15 # 15 minutes
        elif blueprint.id == BlueprintType.WARRIOR_HUT:
            blueprint.buildtime = 60 * 20 # 20 minutes
        elif blueprint.id == 0:  # Dummy
            blueprint.buildtime = 0
        else:
            raise ValueError(f"Unknown blueprint id {blueprint.id}")

    session.commit()
    print("Done")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint', schema=None) as batch_op:
        batch_op.drop_column('buildtime')

    # ### end Alembic commands ###
