"""CHECK constraints on enums

Revision ID: 003d11459d65
Revises: 5530022ea50b
Create Date: 2024-03-17 16:10:27.902391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003d11459d65'
down_revision = '5530022ea50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MAGIC', name='towerbuildingtype').create(op.get_bind())
    sa.Enum('CRYSTAL', name='minebuildingtype').create(op.get_bind())
    with op.batch_alter_table('mine_building', schema=None) as batch_op:
        batch_op.alter_column('mine_type',
                              existing_type=sa.VARCHAR(),
                              type_=sa.Enum('CRYSTAL', name='minebuildingtype'),
                              existing_nullable=False,
                              postgresql_using='mine_type::minebuildingtype')

    with op.batch_alter_table('tower_building', schema=None) as batch_op:
        batch_op.alter_column('tower_type',
                              existing_type=sa.VARCHAR(),
                              type_=sa.Enum('MAGIC', name='towerbuildingtype'),
                              existing_nullable=False,
                              postgresql_using='tower_type::towerbuildingtype')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tower_building', schema=None) as batch_op:
        batch_op.alter_column('tower_type',
                              existing_type=sa.Enum('MAGIC', name='towerbuildingtype'),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)

    with op.batch_alter_table('mine_building', schema=None) as batch_op:
        batch_op.alter_column('mine_type',
                              existing_type=sa.Enum('CRYSTAL', name='minebuildingtype'),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)

    sa.Enum('CRYSTAL', name='minebuildingtype').drop(op.get_bind())
    sa.Enum('MAGIC', name='towerbuildingtype').drop(op.get_bind())
    # ### end Alembic commands ###

