"""added mine collected gem

Revision ID: 00a1af2460d0
Revises: 1fba2ac9af76
Create Date: 2024-03-18 20:50:05.362426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a1af2460d0'
down_revision = '1fba2ac9af76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mine_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('gem_mine_id_fkey', 'mine_building', ['mine_id'], ['placeable_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.drop_constraint('gem_mine_id_fkey', type_='foreignkey')
        batch_op.drop_column('mine_id')

    # ### end Alembic commands ###
