"""added ondelete cascade policy

Revision ID: 081d41bb3cad
Revises: e18abe977e53
Create Date: 2024-04-14 15:10:42.567044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081d41bb3cad'
down_revision = 'e18abe977e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_spells', schema=None) as batch_op:
        batch_op.drop_constraint('player_spells_player_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('player_spells_spell_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('player_spells_player_id_fkey', 'player', ['player_id'], ['user_profile_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('player_spells_spell_id_fkey', 'spell', ['spell_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_spells', schema=None) as batch_op:
        batch_op.drop_constraint('player_spells_player_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('player_spells_spell_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('player_spells_spell_id_fkey', 'spell', ['spell_id'], ['id'])
        batch_op.create_foreign_key('player_spells_player_id_fkey', 'player', ['player_id'], ['user_profile_id'])

    # ### end Alembic commands ###
