"""settings revision

Revision ID: 1238f3f93719
Revises: 165f0ff03e29
Create Date: 2024-05-21 15:05:12.777090

"""
from alembic import op
import sqlalchemy as sa

from src.model.player import Player
from src.model.user_settings import UserSettings

# revision identifiers, used by Alembic.
revision = '1238f3f93719'
down_revision = '165f0ff03e29'
branch_labels = None
depends_on = None


def upgrade():
    # Fuck the previous layout
    # with op.batch_alter_table('player', schema=None) as batch_op:
    #     batch_op.drop_constraint('player_user_profile_id_fkey1', type_='foreignkey')

    op.drop_table('user_settings')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('Player', sa.BigInteger(), nullable=False),
    sa.Column('audio_volume', sa.SmallInteger(), nullable=False),
    sa.Column('performance', sa.SmallInteger(), nullable=False),
    sa.Column('selected_cursor', sa.SmallInteger(), nullable=False),
    sa.Column('horz_sensitivity', sa.SmallInteger(), nullable=False),
    sa.Column('vert_sensitivity', sa.SmallInteger(), nullable=False),
    sa.Column('move_fwd_key', sa.String(length=12), nullable=False),
    sa.Column('move_fwd_val', sa.String(length=12), nullable=True),
    sa.Column('move_bkwd_key', sa.String(length=12), nullable=False),
    sa.Column('move_bkwd_val', sa.String(length=12), nullable=True),
    sa.Column('move_left_key', sa.String(length=12), nullable=False),
    sa.Column('move_left_val', sa.String(length=12), nullable=True),
    sa.Column('move_right_key', sa.String(length=12), nullable=False),
    sa.Column('move_right_val', sa.String(length=12), nullable=True),
    sa.Column('jump_key', sa.String(length=12), nullable=False),
    sa.Column('jump_val', sa.String(length=12), nullable=True),
    sa.Column('interact_key', sa.String(length=12), nullable=False),
    sa.Column('interact_val', sa.String(length=12), nullable=True),
    sa.Column('eat_key', sa.String(length=12), nullable=False),
    sa.Column('eat_val', sa.String(length=12), nullable=True),
    sa.Column('chat_key', sa.String(length=12), nullable=False),
    sa.Column('chat_val', sa.String(length=12), nullable=True),
    sa.Column('slot_1_key', sa.String(length=12), nullable=False),
    sa.Column('slot_1_val', sa.String(length=12), nullable=True),
    sa.Column('slot_2_key', sa.String(length=12), nullable=False),
    sa.Column('slot_2_val', sa.String(length=12), nullable=True),
    sa.Column('slot_3_key', sa.String(length=12), nullable=False),
    sa.Column('slot_3_val', sa.String(length=12), nullable=True),
    sa.Column('slot_4_key', sa.String(length=12), nullable=False),
    sa.Column('slot_4_val', sa.String(length=12), nullable=True),
    sa.Column('slot_5_key', sa.String(length=12), nullable=False),
    sa.Column('slot_5_val', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['Player'], ['player.user_profile_id'], ),
    sa.PrimaryKeyConstraint('Player')
    )

    op.create_check_constraint('ck_audio_volume', 'user_settings', 'audio_volume >= 0 AND audio_volume <= 100')
    op.create_check_constraint('ck_performance', 'user_settings', 'performance >= 0 AND performance <= 2')
    op.create_check_constraint('ck_selected_cursor', 'user_settings', 'selected_cursor >= 0 AND selected_cursor <= 3')
    op.create_check_constraint('ck_horz_sensitivity', 'user_settings', 'horz_sensitivity >= 0 AND horz_sensitivity <= 100')
    op.create_check_constraint('ck_vert_sensitivity', 'user_settings', 'vert_sensitivity >= 0 AND vert_sensitivity <= 100')


    # A bit of data migration
    session = sa.orm.Session(bind=op.get_bind())
    for player in session.query(Player).all():
        session.execute(sa.text(f"INSERT INTO user_settings (\"Player\", audio_volume, performance, selected_cursor, horz_sensitivity, vert_sensitivity, move_fwd_key, move_bkwd_key, move_left_key, move_right_key, jump_key, interact_key, eat_key, chat_key, slot_1_key, slot_2_key, slot_3_key, slot_4_key, slot_5_key) VALUES ({player.user_profile_id}, 100, 2, 0, 50, 50, 'KeyW', 'KeyS', 'KeyA', 'KeyD', 'Space', 'KeyE', 'KeyQ', 'KeyC', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5')"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')

    # Rebuild old table
    op.create_table('user_settings',
                    sa.Column('Player', sa.BigInteger(), nullable=False),
                    sa.Column('audio_volume', sa.SmallInteger(), nullable=False, default=100, server_default='100'),
                    sa.Column('sound_fx', sa.Boolean(), nullable=False, default=True, server_default='true'),
                    sa.Column('background_music', sa.Boolean(), nullable=False, default=True, server_default='true'),
                    sa.Column('move_fwd', sa.String(length=5), nullable=False, default='W', server_default='W'),
                    sa.Column('move_bkwd', sa.String(length=5), nullable=False, default='S', server_default='S'),
                    sa.Column('move_left', sa.String(length=5), nullable=False, default='A', server_default='A'),
                    sa.Column('move_right', sa.String(length=5), nullable=False, default='D', server_default='D'),
                    sa.Column('jump', sa.String(length=5), nullable=False, default='Space', server_default='Space'),
                    sa.Column('inventory', sa.String(length=5), nullable=False, default='E', server_default='E'),
                    sa.Column('pause', sa.String(length=5), nullable=False, default='Esc', server_default='Esc'),
                    sa.Column('attack', sa.String(length=5), nullable=False, default='lmb', server_default='lmb'),
                    sa.ForeignKeyConstraint(['Player'], ['player.user_profile_id'], ),
                    sa.PrimaryKeyConstraint('Player')
                    )
    # with op.batch_alter_table('player', schema=None) as batch_op:
    #     batch_op.create_foreign_key('player_user_profile_id_fkey1', 'user_profile', ['user_profile_id'], ['id'])

    session = sa.orm.Session(bind=op.get_bind())
    for player in session.query(Player).all():
        session.execute(sa.text(f"INSERT INTO user_settings (\"Player\") VALUES ({player.user_profile_id})")) # SQLInjection letsgoooo (nah jk)

    # ### end Alembic commands ###
