"""add fuse task

Revision ID: 165f0ff03e29
Revises: 6191c665b885
Create Date: 2024-05-21 14:01:20.773580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165f0ff03e29'
down_revision = '6191c665b885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuse_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crystal_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_check_constraint('ck_crystal_amount', 'fuse_task', 'crystal_amount >= 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_crystal_amount', 'fuse_task', type_='check')
    op.drop_table('fuse_task')
    # ### end Alembic commands ###
