"""add last_login last_logout to player

Revision ID: 16d5df0c381c
Revises: aa541bef480
Create Date: 2024-04-09 16:41:29.412542

"""
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d5df0c381c'
down_revision = 'aa541bef480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_logout', sa.DateTime(), nullable=False, server_default=str(datetime.datetime(1970, 1, 1, 0, 0))))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=False, server_default=sa.text('now()')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('last_logout')

    # ### end Alembic commands ###
