"""add building gem inventory

Revision ID: 1fba2ac9af76
Revises: 5ba45cc2c583
Create Date: 2024-03-18 20:07:31.266382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fba2ac9af76'
down_revision = '5ba45cc2c583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('gem_building_id_fkey', 'building', ['building_id'], ['placeable_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.drop_constraint('gem_building_id_fkey', type_='foreignkey')
        batch_op.drop_column('building_id')

    # ### end Alembic commands ###
