"""added tasks and relations

Revision ID: 3e6ef903eb77
Revises: 0020f481c86d
Create Date: 2024-04-01 16:44:12.862156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6ef903eb77'
down_revision = '0020f481c86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('starttime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('endtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handeled', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('island_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['island.owner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_upgrade_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('to_level', sa.SmallInteger(), nullable=False),
    sa.Column('used_crystals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_minion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('builds_on_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('builder_minion_builds_on_id_fkey', 'building_upgrade_task', ['builds_on_id'], ['id'])

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('building_task_id_fkey', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_constraint('building_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('builder_minion', schema=None) as batch_op:
        batch_op.drop_constraint('builder_minion_builds_on_id_fkey', type_='foreignkey')
        batch_op.drop_column('builds_on_id')

    op.drop_table('building_upgrade_task')
    op.drop_table('task')
    # ### end Alembic commands ###
