"""initial setup

Revision ID: 46a717cd6d5c
Revises: 
Create Date: 2024-03-19 20:01:59.035787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a717cd6d5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('credentials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('user_profile_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('user_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('crystals', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('user_profile_id')
    )
    op.create_table('password_credentials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=False),
    sa.Column('password_salt', sa.LargeBinary(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_credentials')
    op.drop_table('player')
    op.drop_table('credentials')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
