"""added placeables and buildings

Revision ID: 5530022ea50b
Revises: 99bc58910c87
Create Date: 2024-03-16 18:53:57.028741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5530022ea50b'
down_revision = '99bc58910c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placeable',
    sa.Column('placeable_id', sa.BigInteger(), nullable=False),
    sa.Column('island_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('xpos', sa.SmallInteger(), nullable=False),
    sa.Column('zpos', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['island.owner_id'], ),
    sa.PrimaryKeyConstraint('placeable_id')
    )
    op.create_table('building',
    sa.Column('placeable_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['placeable_id'], ['placeable.placeable_id'], ),
    sa.PrimaryKeyConstraint('placeable_id')
    )
    op.create_table('mine_building',
    sa.Column('placeable_id', sa.BigInteger(), nullable=False),
    sa.Column('mine_type', sa.String(), nullable=False),
    sa.Column('mined_amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['placeable_id'], ['building.placeable_id'], ),
    sa.PrimaryKeyConstraint('placeable_id')
    )
    op.create_table('tower_building',
    sa.Column('placeable_id', sa.BigInteger(), nullable=False),
    sa.Column('tower_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['placeable_id'], ['building.placeable_id'], ),
    sa.PrimaryKeyConstraint('placeable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tower_building')
    op.drop_table('mine_building')
    op.drop_table('building')
    op.drop_table('placeable')
    # ### end Alembic commands ###
