"""removed blueprint-player assoc

Revision ID: 5944ad05a0ae
Revises: 974781309af7
Create Date: 2024-05-13 15:58:22.188773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5944ad05a0ae'
down_revision = '974781309af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blueprint_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprint_association',
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('blueprint_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprint.id'], name='blueprint_association_blueprint_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['player.user_profile_id'], name='blueprint_association_player_id_fkey')
    )
    # ### end Alembic commands ###
