"""add gems

Revision ID: 5ba45cc2c583
Revises: 6c0d6ff4113b
Create Date: 2024-03-18 18:45:06.454495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ba45cc2c583'
down_revision = '6c0d6ff4113b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type in advance
    sa.Enum('JUMMY', name='gemtype').create(op.get_bind())

    op.create_table('gem',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', postgresql.ENUM('JUMMY', name='gemtype', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gem_attribute',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('gem_attribute_association',
    sa.Column('gem_id', sa.BigInteger(), nullable=False),
    sa.Column('gem_attribute_id', sa.SmallInteger(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gem_attribute_id'], ['gem_attribute.id'], ),
    sa.ForeignKeyConstraint(['gem_id'], ['gem.id'], ),
    sa.PrimaryKeyConstraint('gem_id', 'gem_attribute_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gem_attribute_association')
    op.drop_table('gem_attribute')
    op.drop_table('gem')

    sa.Enum('JUMMY', name='gemtype').drop(op.get_bind())
    # ### end Alembic commands ###
