"""Add cascades

Revision ID: 5d7ce9d42777
Revises: 00aa5ef93b81
Create Date: 2024-04-24 19:42:02.463162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7ce9d42777'
down_revision = '00aa5ef93b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building_upgrade_task', schema=None) as batch_op:
        batch_op.drop_constraint('building_upgrade_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('building_upgrade_task_id_fkey', 'task', ['id'], ['id'], onupdate='cascade', ondelete='cascade')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint('chat_message_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('chat_message_user_id_fkey', 'player', ['user_id'], ['user_profile_id'], ondelete='set null')

    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.drop_constraint('island_altar_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('island_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('island_owner_id_fkey', 'player', ['owner_id'], ['user_profile_id'], ondelete='cascade', use_alter=True)
        batch_op.drop_column('altar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building_upgrade_task', schema=None) as batch_op:
        batch_op.drop_constraint('building_upgrade_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('building_upgrade_task_id_fkey', 'task', ['id'], ['id'])

    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altar_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('island_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('island_owner_id_fkey', 'player', ['owner_id'], ['user_profile_id'])
        batch_op.create_foreign_key('island_altar_id_fkey', 'building', ['altar_id'], ['placeable_id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint('chat_message_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('chat_message_user_id_fkey', 'player', ['user_id'], ['user_profile_id'])

    # ### end Alembic commands ###
