"""added player stats

Revision ID: 6191c665b885
Revises: ef76950d6c07
Create Date: 2024-05-20 15:33:29.729492

"""
from alembic import op
import sqlalchemy as sa

from src.model.player import Player
from src.model.player_stats import PlayerStats

# revision identifiers, used by Alembic.
revision = '6191c665b885'
down_revision = 'ef76950d6c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_kills', sa.Integer(), nullable=True),
    sa.Column('player_deaths', sa.Integer(), nullable=True),
    sa.Column('minions_killed', sa.Integer(), nullable=True),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('damage_taken', sa.Integer(), nullable=True),
    sa.Column('mana_spent', sa.Integer(), nullable=True),
    sa.Column('spell_casts', sa.Integer(), nullable=True),
    sa.Column('gems_won', sa.Integer(), nullable=True),
    sa.Column('gems_lost', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.user_profile_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )

    # CHECK constraints
    op.create_check_constraint('ck_player_kills', 'player_stats', 'player_kills >= 0')
    op.create_check_constraint('ck_player_deaths', 'player_stats', 'player_deaths >= 0')
    op.create_check_constraint('ck_minions_killed', 'player_stats', 'minions_killed >= 0')
    op.create_check_constraint('ck_damage_dealt', 'player_stats', 'damage_dealt >= 0')
    op.create_check_constraint('ck_damage_taken', 'player_stats', 'damage_taken >= 0')
    op.create_check_constraint('ck_mana_spent', 'player_stats', 'mana_spent >= 0')
    op.create_check_constraint('ck_spell_casts', 'player_stats', 'spell_casts >= 0')
    op.create_check_constraint('ck_gems_won', 'player_stats', 'gems_won >= 0')
    op.create_check_constraint('ck_gems_lost', 'player_stats', 'gems_lost >= 0')
    op.create_check_constraint('ck_games_played', 'player_stats', 'games_played >= 0')
    op.create_check_constraint('ck_games_won', 'player_stats', 'games_won >= 0')
    # ### end Alembic commands ###


    # Data migration
    session = sa.orm.Session(bind=op.get_bind())
    for player in session.query(Player):
        player_stats = PlayerStats(player_id=player.user_profile_id)
        session.add(player_stats)
    session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    # ### end Alembic commands ###
