"""added altar one to one

Revision ID: 6c0d6ff4113b
Revises: 003d11459d65
Create Date: 2024-03-17 18:59:45.946037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0d6ff4113b'
down_revision = '003d11459d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altar_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('island_altar_id_fkey', 'building', ['altar_id'], ['placeable_id'], use_alter=True)


def downgrade():


    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.drop_constraint('island_altar_id_fkey', type_='foreignkey')
        batch_op.drop_column('altar_id')

    # ### end Alembic commands ###
