"""add xp rotation ypos

Revision ID: 7c72288cfcca
Revises: f5ce112a488a
Create Date: 2024-03-28 18:42:02.067438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c72288cfcca'
down_revision = 'f5ce112a488a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ypos', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('placeable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation', sa.SmallInteger(), nullable=False, server_default='0'))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('xp')

    with op.batch_alter_table('placeable', schema=None) as batch_op:
        batch_op.drop_column('rotation')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('ypos')

    # ### end Alembic commands ###
