"""oauth2 login

Revision ID: 7fe22a0c51ee
Revises: b3100d499c70
Create Date: 2024-03-07 16:38:16.102775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe22a0c51ee'
down_revision = 'b3100d499c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth2_credentials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sso_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('o_auth2_credentials')
    # ### end Alembic commands ###
