"""add player gem relation

Revision ID: 875e85441cdc
Revises: 00a1af2460d0
Create Date: 2024-03-18 22:39:30.960627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875e85441cdc'
down_revision = '00a1af2460d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('gem_player_id_fkey', 'player', ['player_id'], ['user_profile_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.drop_constraint('gem_player_id_fkey', type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
