"""Moved task association to placeable

Revision ID: 8adfc09eedeb
Revises: c3d38ae6f606
Create Date: 2024-04-27 16:37:52.739003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adfc09eedeb'
down_revision = 'c3d38ae6f606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_constraint('building_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('placeable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('placeable_task_id_fkey', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeable', schema=None) as batch_op:
        batch_op.drop_constraint('placeable_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('building_task_id_fkey', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###
