"""added friends

Revision ID: 8b082442ee8a
Revises: 5d7ce9d42777
Create Date: 2024-04-24 23:05:01.173036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b082442ee8a'
down_revision = '5d7ce9d42777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('sender_id != receiver_id'),
    sa.ForeignKeyConstraint(['receiver_id'], ['player.user_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['player.user_profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='unique_sender_receiver')
    )
    op.create_table('friends_association',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('friend_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('player_id != friend_id'),
    sa.ForeignKeyConstraint(['friend_id'], ['player.user_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.user_profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'friend_id')
    )
    with op.batch_alter_table('blueprint_association', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('blueprint_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprint_association', schema=None) as batch_op:
        batch_op.alter_column('blueprint_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('player_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    op.drop_table('friends_association')
    op.drop_table('friend_request')
    # ### end Alembic commands ###
