"""added match queue table

Revision ID: 974781309af7
Revises: a6472f989c0c
Create Date: 2024-04-28 19:30:22.004646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974781309af7'
down_revision = 'a6472f989c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_queue',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.user_profile_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_queue')
    # ### end Alembic commands ###
