"""island and entities

Revision ID: 99bc58910c87
Revises: 22389b2496cb
Create Date: 2024-03-12 20:51:55.037912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bc58910c87'
down_revision = '22389b2496cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('island',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['player.user_profile_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('entity',
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('island_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('xpos', sa.Integer(), nullable=False),
    sa.Column('zpos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['island.owner_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('builder_minion',
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builder_minion')
    op.drop_table('entity')
    op.drop_table('island')
    # ### end Alembic commands ###
