"""moved level to entity superclass

Revision ID: a30fac7d53b1
Revises: aa156f1b0d9e
Create Date: 2024-04-06 15:17:28.532961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30fac7d53b1'
down_revision = 'aa156f1b0d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder_minion', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BIGINT(), autoincrement=False, nullable=False, server_default='0'))

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('builder_minion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))

    # ### end Alembic commands ###
