"""added entries to GemType enum

Revision ID: a547169fac51
Revises: 8b082442ee8a
Create Date: 2024-04-26 21:54:55.235623

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'a547169fac51'
down_revision = '8adfc09eedeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'gemtype', ['JUMMY', 'RUBY', 'SAPPHIRE', 'DIAMOND', 'EMERALD', 'AMETHYST', 'AMBER'],
                        [TableReference(table_schema='public', table_name='gem', column_name='type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
    op.execute("INSERT INTO gem_attribute (id, type) VALUES (0, 'speed')")
    op.execute("INSERT INTO gem_attribute (id, type) VALUES (1, 'damage')")
    op.execute("INSERT INTO gem_attribute (id, type) VALUES (2, 'fortune')")
    op.execute("INSERT INTO gem_attribute (id, type) VALUES (3, 'capacity')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'gemtype', ['JUMMY'],
                        [TableReference(table_schema='public', table_name='gem', column_name='type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
    op.execute("DELETE FROM gem_attribute WHERE id = 0")
    op.execute("DELETE FROM gem_attribute WHERE id = 1")
    op.execute("DELETE FROM gem_attribute WHERE id = 2")
    op.execute("DELETE FROM gem_attribute WHERE id = 3")
