"""made player_id on gem non-nullable

Revision ID: c3d38ae6f606
Revises: 8b082442ee8a
Create Date: 2024-04-27 16:25:53.595554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d38ae6f606'
down_revision = '8b082442ee8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gem', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
