"""add props

Revision ID: da4440350a99
Revises: 3e6ef903eb77
Create Date: 2024-04-01 20:18:48.519158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4440350a99'
down_revision = '3e6ef903eb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prop',
    sa.Column('placeable_id', sa.BigInteger(), nullable=False),
    sa.Column('prop_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['placeable_id'], ['placeable.placeable_id'], ),
    sa.PrimaryKeyConstraint('placeable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prop')
    # ### end Alembic commands ###
