"""updated player obj to er diagram

Revision ID: dc57db68b859
Revises: 7fe22a0c51ee
Create Date: 2024-03-11 13:03:18.731394

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dc57db68b859'
down_revision = '7fe22a0c51ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mana', sa.Integer(), nullable=False, default=0, server_default='0 '))
        batch_op.alter_column('xp', nullable=False, new_column_name='level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('level', nullable=False, new_column_name='xp')
        batch_op.drop_column('mana')

    # ### end Alembic commands ###
