"""removed handled column from task table

Revision ID: e18abe977e53
Revises: 16d5df0c381c
Create Date: 2024-04-09 17:17:44.969927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18abe977e53'
down_revision = '16d5df0c381c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('handeled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handeled', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###
