"""added user settings

Revision ID: e45e77b4563c
Revises: 7c72288cfcca
Create Date: 2024-03-30 12:13:43.965497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45e77b4563c'
down_revision = '7c72288cfcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('Player', sa.BigInteger(), nullable=False),
    sa.Column('audio_volume', sa.SmallInteger(), nullable=False),
    sa.Column('sound_fx', sa.Boolean(), nullable=False),
    sa.Column('background_music', sa.Boolean(), nullable=False),
    sa.Column('move_fwd', sa.String(length=5), nullable=False),
    sa.Column('move_bkwd', sa.String(length=5), nullable=False),
    sa.Column('move_left', sa.String(length=5), nullable=False),
    sa.Column('move_right', sa.String(length=5), nullable=False),
    sa.Column('jump', sa.String(length=5), nullable=False),
    sa.Column('inventory', sa.String(length=5), nullable=False),
    sa.Column('pause', sa.String(length=5), nullable=False),
    sa.Column('attack', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['Player'], ['player.user_profile_id'], ),
    sa.PrimaryKeyConstraint('Player')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_foreign_key('player_user_profile_id_fkey1', 'user_profile', ['user_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_user_profile_id_fkey1', type_='foreignkey')

    op.drop_table('user_settings')
    # ### end Alembic commands ###
