"""added player entity

Revision ID: f5ce112a488a
Revises: 47b8f28490b1
Create Date: 2024-03-22 15:26:04.194338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ce112a488a'
down_revision = '47b8f28490b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_entity',
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('Player', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['Player'], ['player.user_profile_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_entity')
    # ### end Alembic commands ###
